#should not write like this it seperates try and except


# try:
#     print('try')
# print('abc')
# except ZeroDivisionError:
#     print('except 1')