try:
    print('try')
except:
    print('except')
finally:
    try:
        print('try')
    except:
        print('except')
    