try:
    try:
       print('inner try')
       
    finally:
        print('finnaly')
except:
    print('except')