#case1

#no exception


try:
    print('try block')

except:
    print('except block ')

finally:
    print('finally block ')

